### ISSUE TITLE
Total loss of bidirectional witnessing

### ISSUE THREAD

**Issue by mibsmibs** [helium/miner#1093]
No witnessing and no witnesses over the last few days. Setup prior to the last few days has been performing above average. This event is effecting two miners. 

1) Total loss https://explorer.helium.com/hotspots/11CHzVUU7CzRmSXjLAmrJz8gnwDPXHf1yUsewwAVXVmf5z2aHu2/activity
2) near total loss https://explorer.helium.com/hotspots/112mtQ8pm4BNZfobUn6FLfREkBSNVazxArpT6qsjdFbwjeQVrj4g/activity

**Comment by Hmpflala** [comment]
Yeah I have the same issue, seems like it's a sensecap problem. 

https://github.com/helium/miner/issues/1091

**Comment by mamartins** [comment]
Same here with a sensecap as well

**Comment by Trinitrophenol81** [comment]
I own a sensecap as well. Normally I have 3-4 Sent Beacons a day, I noticed that for the past 4+ days , the sent beacons daily are 0 or at most once a day, with 0 witness (I get up to 9-10 witness normally). Witnessed beacons is also affected, with lesser frequency .  
https://explorer.helium.com/hotspots/112mDa9zzokVMyUFEmPNNDc64dBEs4HVjEqUaqAE47njSN9QRm1y/activity

**Comment by mibsmibs** [comment]
Update, no change totally 0 witnessing events in any direction
![10_1](https://user-images.githubusercontent.com/85662068/135611364-8e7baad8-c9d4-4981-bd9b-1be656234a69.png)
.

**Comment by gdanskgrom** [comment]
Similarly for me on several sensecaps, 2 raks and bobcat.  In my cases, outbound connections are dropping often.  Reboots help but issue returns.

**Comment by axkman** [comment]
Same problem for me, I have a Sensecap aswell.

**Comment by bitlite** [comment]
Log into your Miner Web Page, Click on RESET MINER, this will clear the firmware and blockchain and start downloading the firmware and build the blockchain again.  After 30 minutes, log back in and click FAST SYNC and wait about 20 minutes.  It should be resolved.  If so, please close this ticket.

**Comment by axkman** [comment]
When I do that, reset blocks, fast sync. It will sometimes go online for a bit on explorer/helium app, but after 60min orso on explorer/helium app it turns back offline. And its still not beaconing.
My investigation about this problem might show it has something to do with p2p network which is not gossipping the hotspots status/information correctly. There are nodes in the p2p network that still contain old information, and they try to connect to the hotspot at wrong ports, then conclude "hotspot is offline, because we couldnt connect to it to the wrong ports based on out-of-date information" so we don't let it beacon or participating in activites.
I see it in my router log that many nodes/hotspots still try to connect on wrong ports to my hotspot. Also when I put my hotspot on relayed, to force new infomation gossip to the p2p network and after, I open port 44158 again. I see how the new information is being gossiped to the p2p network. But still nodes contain old port/ip/status info and they try to connect to my hotspot on wrong ports. After 60min of trying to connect to my hotspot on wrong ports, the p2p network decides my hotspot is offline. Then no chance of it starting to beacon.

So I hugely suspect this problem of not beaconing has something to do with incorrect gossiping or updating the current hotspote state/status/ip/port information to the p2p network. Like some nodes still stubborn contain out-of-date information. While those nodes/hotspots should also contain the current information - so they should connect to the hotspot on port 44158 instead of trying all other kinds of ports  (those other ports the p2p network has is out-of-date hotspot status information from when my hotspot was relayed so it gave random ports to the p2p network/api).

**Comment by abhay** [comment]
This report is somewhat old so I'm going to close it for now. Hopefully you've seen some improvement since the more recent releases. Please verify that your Hotspot is updated to the latest version, wait a few days to see if activity has resumed and then, if not, please post in the pinned issue with more details on what you're seeing.
