### ISSUE TITLE
Did the 2021.11.30.1 update solve the problem of not sending beacon and not having a witness for you?

### ISSUE THREAD

**Issue by Mikael1993** [helium/miner#1273]
This update has not affected me

**Comment by Chris-S44** [comment]
This update stopped 3 of my perfectly working miners. They do not witness or beacon at all. They are just creating challenges

**Comment by Pappa-Bear** [comment]
No change for my miners on LTE...still only challenging every 8 hours or so, and maybe 1 or 2 witnesses in a day if I'm lucky

**Comment by Davekted** [comment]
Still no changes.

![image](https://user-images.githubusercontent.com/95023956/144560800-47c29d43-2c30-4f0d-8f28-bc6cc94e2fbf.png)
from activity every few minutes to some in 4 / 6 hours

**Comment by taoteh1221** [comment]
Seemed better afterwards for me. Everybody in my area seems to be back to normal as well. Bobcats / Sensecaps / Calchip devices.

**Comment by cany25** [comment]
No change for my bobcat on LTE, only activity is data transfer and some challenges, last beacon 25 days ago.
![grafik](https://user-images.githubusercontent.com/87498131/144584041-a73fe78b-9872-41b2-b06e-fea426681aa0.png)

**Comment by mathoso** [comment]
no

![image](https://user-images.githubusercontent.com/72282420/144593199-b39c6c06-46d9-4766-970b-ce87ade42c11.png)
![image](https://user-images.githubusercontent.com/72282420/144593243-1f8a9fcd-f979-4032-83a3-7822ce5cf7c3.png)
![image](https://user-images.githubusercontent.com/72282420/144593304-0f2afd36-23c9-4014-9a51-b4b30f685b9c.png)

with 3rd one I did internet provider and public IP change, but numbers are still terrible, under 20% of miners in near hexes

**Comment by ElYoM** [comment]
Still the same for me after the update : absolutely no beaconing with my 3 hotspots since october 28th. All 3 were perfectly functional before this date, are perfectly configured, up to date, unrelayed and synchronized. Each on a 1Gbps fiber connection.
Even worse, a fourth hotspot that just arrived in my city (yes, there are only 4 at the moment) has the exact same problem.
The legitimate question that is starting to arise: how long does it take for a miner who doesn't mine to be considered a scam? This is the question I was asked by colleagues I convinced to buy hotspots to join me in this project when they now see this problem going on for over a month. What should I tell them?
![earnings_wow](https://user-images.githubusercontent.com/18171050/144593905-a5c60473-de6d-4447-bab1-2d5f3f9efa0a.png)

**Comment by Mikael1993** [comment]
Worst of all, someone from the damn helium team is not responding
![image](https://user-images.githubusercontent.com/94840296/144604942-f5c1d94d-e0f7-4178-9bcc-bf6b9531fef7.png)

**Comment by wetsqueegee** [comment]
My RAK v.2 was fixed, my OG hotspot still no witnesses, no challenges, no creating challenges.

**Comment by amirhaleem** [comment]
can you share some hotspot names in this thread (I see yours @ElYoM thanks)? graphs of earnings are not particularly helpful, given that they can be down as much as 90% due to all the increased PoC activity

**Comment by wetsqueegee** [comment]
Merry champagne wallaby

**Comment by mathoso** [comment]
Noisy Lavender Fly
Blunt Infrared Badger
Powerful Tangerine Rabbit

**Comment by Mikael1993** [comment]
- Stable Bronze Puppy
- Sticky Graphite Liger
- Crazy Magenta Pig
- Cool Stone Sheep
- Harsh Orange Millipede
- Narrow Hazelnut Swift

If some of these are relays, I have relayed them myself
Maybe after 1 month our situation will get better
I saw that it is useless to relayed

**Comment by mathoso** [comment]
btw I understand rewards are lower, but not for miners in near hexes, so it is some other network issue, there are still rewards up to 1hnt daily in my area (example Zesty Ultraviolet Sparrow), but 2 bobcats are flat, and 1 is still working under 20% after public IP change (powerful tangerine rabbit)

![image](https://user-images.githubusercontent.com/72282420/144634073-de3793bc-1fbe-44da-b471-a3e1c8ce360a.png)

**Comment by Davekted** [comment]
> can you share some hotspot names in this thread (I see yours @ElYoM thanks)? graphs of earnings are not particularly helpful, given that they can be down as much as 90% due to all the increased PoC activity

https://explorer.helium.com/hotspots/11QGUWZjMpHM1rrRfrm8xo88gTJkDPgxY2b497FFBuM5xWLoMmh
https://explorer.helium.com/hotspots/11HhVrBs2s2xwESKXfehhwJn2PKccKxV1o3rnaKTFWhn45ZwAdS/activity

**Comment by Chris-S44** [comment]
Fierce charcoal crab - fibre
Melodic brown swallow - lte
Atomic pineapple cow - fibre

**Comment by samilbeden** [comment]
Bumpy Admiral Crocodile
https://explorer.helium.com/hotspots/1124X7sv4E1AvqiPWMuDUTwQKbKRkM7tnpG3Bw3AuTL7XQWcCj7R

**Comment by amirhaleem** [comment]
thanks, that's good enough for now. we'll report back soon

**Comment by samilbeden** [comment]
> thanks, that's good enough for now. we'll report back soon

Also i've created a ticket #80513 via web page.

**Comment by hcl-83** [comment]
Dancing Lipstick Puppy
Short Viridian Rattlesnake
Both on lte both no POC activity for long time.

**Comment by ElYoM** [comment]
> can you share some hotspot names in this thread (I see yours @ElYoM thanks)? graphs of earnings are not particularly helpful, given that they can be down as much as 90% due to all the increased PoC activity

@amirhaleem Just in case, my 3 hotspots :
Small Charcoal Nightingale https://explorer.helium.com/hotspots/11xXV4V8marSnCoVRbFWtZZgXstsXXY84P68Hn8boxVFUEoJDj9
Fun Punch Ram https://explorer.helium.com/hotspots/1123CoUsmffo1qTYEB8h1KsC7JrZ8dYk8Xz5EqQMDx5Jav7i3yTJ
Wonderful Lime Lynx https://explorer.helium.com/hotspots/11ANbw714zMX4UgkwUVBkohdNMcAeZHBdBxYdqYqYHhtviXfYRW

And the last one that just arrived in my city but is not mine. Same problem as the 3 others, no beacon since its installation several days ago.
Low Tiger Oyster https://explorer.helium.com/hotspots/11YdsNeDpPD4a2tffM3oU6RGbfofH13xP4ZAUwXMstjXtPLCLvN

Thank you in advance for the help you can give us to solve this problem, we feel a bit alone on the subject now. Especially since this is starting to have real consequences on the planned deployment of other hotspots in my city, a person who just received his two Controllino hotspots tell me that he doesn't want to install them anymore at the risk of ending up with hotspots that don't mine for weeks like me and I can't blame him. He now wants to resell them and I'm afraid everyone else wants to do the same. Too bad for the network coverage...

**Comment by Allstarsone** [comment]
no, my miner totally dead rarely sending beacon *Shambolic Fuchsia Bird*

**Comment by Mikael1993** [comment]
I think we are just to make the world greener
Without any reward or hope
And it does not matter to anyone

**Comment by JeroenIoT** [comment]
Dead and flatlined - https://api.helium.io/v1/hotspots/name/generous-cider-poodle

![image](https://user-images.githubusercontent.com/14053463/144669109-a39149ca-0321-4e13-92bb-71e4e0c07c55.png)

**Comment by Mikael1993** [comment]
3-month chart
All of them are dead

![Untitled-1 copy](https://user-images.githubusercontent.com/94840296/144702830-06657f01-8169-4a82-aac8-27055f4129a3.jpg)

**Comment by Chris-S44** [comment]
@amirhaleem I see more and more around me going down. They are now just challenging beaconers. Some people are getting a little activity back by opening port 44159 instead but this is certainly not the answer and will hurt the network

**Comment by Pappa-Bear** [comment]
> can you share some hotspot names in this thread (I see yours @ElYoM thanks)? graphs of earnings are not particularly helpful, given that they can be down as much as 90% due to all the increased PoC activity

I've moved all but one of them off of the LTE as hosts kindly allowed me to use their wifi (although relayed). I have left 1 miner on LTE as my 'control' - [Generous Saffron Otter](https://explorer.helium.com/hotspots/11AU5Maxe6xHkYdvVscY1WYs54KWXN7coWZfJ1qdQ7g1zFNKsC8)

I've paused the deployment of my fleet or 22 miners till this is resolved as 21 of them were to use LTE..but I'm still paying for 21 LTE contracts each month while we get this resolved...so fingers crossed we can fix it quickly.

Please feel free to reach out it you want more info, to test anything or for more detailed access/info to my 'control' miner left on LTE.

**Comment by SeroSerhan** [comment]
I also have the same problem. I tried every possible workaround at Helium and Sensecap Discords, but still getting flatlined after the last firmware update. Before that everything was working fine. As last resort, now going back to dynamic IP instead of static public IP as support said getting relayed may solve the issue. But I believe and as i read lots of people having the same issue, it looks like a problem at the firmware side
[Real Pistachio Opossum](https://explorer.helium.com/hotspots/112kATHoGFJg2kcB2CbxH16wGPBt2BLRv625CoU2zLtsewNwdP45)

**Comment by Chris-S44** [comment]
> > can you share some hotspot names in this thread (I see yours @ElYoM thanks)? graphs of earnings are not particularly helpful, given that they can be down as much as 90% due to all the increased PoC activity
> 
> @amirhaleem
> 
> I've moved all but one of them off of the LTE as hosts kindly allowed me to use their wifi (although relayed). I have left 1 miner on LTE as my 'control' - [Generous Saffron Otter](https://explorer.helium.com/hotspots/11AU5Maxe6xHkYdvVscY1WYs54KWXN7coWZfJ1qdQ7g1zFNKsC8)
> 
> This miner is in a decent location with a good mast and antenna setup (which I upgraded when it first flatlined in case this was the issue), UPS and really strong LTE signal.
> 
> I've paused the deployment of my fleet or 22 miners till this is resolved as 21 of them were to use LTE..but I'm still paying for 21 LTE contracts each month while we get this resolved...so fingers crossed we can fix it quickly.
> 
> Please feel free to reach out it you want more info, to test anything or for more detailed access/info to my 'control' miner left on LTE.

Unfortunately it's not just an LTE problem anymore. They were the first to be affected but now mine on fiber and adsl are affected

**Comment by Mikael1993** [comment]
Both networks are almost identical
Both networks are all Babket
Both are not relays and are well configured
But look at it
See us too
![Untitled-1 copy](https://user-images.githubusercontent.com/94840296/144709005-0c77e79a-d96e-41b9-9884-0e199cf214df.jpg)

**Comment by hezuyuan** [comment]
Haven't any beacon issued a month! I think this project really stink!

![e3a5ff406adc5fbea6439762f9e7003](https://user-images.githubusercontent.com/82560348/144712709-27fd6289-e25e-498a-8ca7-e0c3c7def0c7.png)

**Comment by amirhaleem** [comment]
we’re testing a new release over the weekend that we’re optimistic will help. assuming there are no issues we’ll GA on Monday

**Comment by wetsqueegee** [comment]
@amirhaleem feel free to use my merry champagne wallaby unit as a test unit if needed

**Comment by jnspsn** [comment]
Unique Jetblack Dinosaur
Custom Honey Wasp
They have been struggling for a month to keep synced. Almost only challenges

**Comment by JeroenIoT** [comment]
> we’re testing a new release over the weekend that we’re optimistic will help. assuming there are no issues we’ll GA on Monday

Out of technical curiosity - what is the cause? (as it seems hotspots go randomly "**flat and dead**")

**Comment by bgdn021** [comment]
@amirhaleem Hoping for the best.

Also as @JeroenIoT asked I would also like to know the cause of this? I've lost much hair due to this and lost lots of hours relocating hotspots, changing ISP, dynamic/static IPs and so on...

**Comment by Mikael1993** [comment]
@amirhaleem
Thank you for your support and cooperation
If possible, tell us and our friends the reason for this problem
We have been involved in this issue day and night until now

**Comment by ricopt5** [comment]
@amirhaleem 

My hotspot stopped witnessing with the last 2021.11.30.1 update. Following the blockchain with no problem.
I changed its public IP but still no witnessing. I then changed ISP entirely and the hotspot started witnessing again.

I've also been doing some investigation.
I did a network capture of my hotspot while it was in the situation where it wasn't witnessing anything and the hotspots around were beaconing.
I then analyzed the hotspots that beaconed around me in that timeframe and got the IP of the corresponding challengers (with the help of heliumstatus.io).
After that, I started searching my network capture for outgoing communication from my hotspot to those challengers.
What I found was that my hotspot was reporting witnessing the beacons to the correct challengers (you can even see in the packets the lora datarate of the signal).

So, my hotspot was indeed receiving the lora beacons and reporting them to the corresponding challengers successfully, but in the eyes of the blockchain my hotspot was never a witness to those beacons. (The beacons have less than 18 witnesses, so there was space for my hotspot to be selected as a witness)

This makes it seem that is not a peerbook problem since the hotspot knew to which IP to connect to report the witnessing.

Hotspot is "Cold Sable Snake"

**Comment by ykuntsevych** [comment]
> can you share some hotspot names in this thread (I see yours @ElYoM thanks)? graphs of earnings are not particularly helpful, given that they can be down as much as 90% due to all the increased PoC activity

Faint Denim Parrot

**Comment by amirhaleem** [comment]
> @amirhaleem
> Thank you for your support and cooperation
> If possible, tell us and our friends the reason for this problem
> We have been involved in this issue day and night until now

would like to confirm the solution actually works before attempting to explain. let's wait for the 12.03 firmware release

**Comment by Mikael1993** [comment]
@amirhaleem
Yes, quite professional and logical

**Comment by jerome-botreau** [comment]
Still nothing, 0 beacons, and 1/50 witnesses…
Please help ! 😞

**Comment by yogeshnichal** [comment]
I have 7 miners they still earn only 0.03-0.05 HNT per day since last 10 days. They were working fine before, It's outdoor setup, Public/static IP 2 on fiber & 5 on 4G LTE.
I am trying to set up an IoT network for my small town so I have all my miners setup close to each other.
Please please help ! 😞
https://explorer.helium.com/accounts/13wvymwxsxw6nDbRa5uE5wm76cyDgM1KNKtJVmnXbzd1tmRbQuA

**Comment by Jamovich** [comment]
There has been an improvement but the issue hasn’t been totally resolved yet

**Comment by JeroenIoT** [comment]
> There has been an improvement but the issue hasn’t been totally resolved yet

GA is only on Monday.

**Comment by techygeekshome** [comment]
Mine are working, but significant drop in rewards since the problems of last month.

Alert Saffron Hedgehog
Hidden Golden Sidewinder

**Comment by ebestek** [comment]
> can you share some hotspot names in this thread (I see yours @ElYoM thanks)? graphs of earnings are not particularly helpful, given that they can be down as much as 90% due to all the increased PoC activity

Chilly Garnet Goat

**Comment by Mikael1993** [comment]
@amirhaleem
Has 3 hotspots
All 3 are relayed
And see income
Is this fair?

https://explorer.helium.com/accounts/13X7nZ6wZTiWtbojmHvXcpi9jgkG4rTB3suePZiuKoheFxPEHhY

**Comment by Davekted** [comment]
well Best Eggplant Butterfly is better !     😥💩💩

**Comment by jakub2907** [comment]
I have had 5 miners flatlined since begining of November. They were working fine before, I changed nothing. Good set up, antenna outside, Public/static IP on LTE. I have 9 miners on LTE. 4 are working fine
After the last update two of them started working. They started to send beacons and witness at a satisfying rate for the area I am in.
3 others are still flatlined, so now I have 6 working on LTE and 3 still down.
I am trying to set up an IoT network for my small town so I have all my miners close.

This one has been down for a month now, and was making over 1HNT a day before (reward were bigger back then, but taking into consideration how it is set up it should be getting around 0.7 now)
https://explorer.helium.com/hotspots/112rLJFZsUjw1sMd29dZUfZuY8jkiCAqeyEHLn4YZ1r9TNPx9qDc

This one was set up on November 7th, worked for a couple of days and stopped as well. Should also be making around 0,5-0,7 if it would start beaconing and witnessing like it should.
https://explorer.helium.com/hotspots/112uukw5t6T1KMUZuxENZdbWrz68UhE6AVafJci7Pcs8TXFXd4bv

Last one that was also beaconing before but stopped. 
https://explorer.helium.com/hotspots/11wmQytt96ufuYhxboq6tW7tVZ6AqRduuwpYoszLS7sdJT4CWnL

**Comment by Jamovich** [comment]
My six hotspots are still effectively useless since beginning November. I heard that there was supposed to be a release on the 3rd of December? Has it been uploaded yet? 

If it has there has been no effect

Thanks

**Comment by Jamovich** [comment]
> > @amirhaleem
> > Thank you for your support and cooperation
> > If possible, tell us and our friends the reason for this problem
> > We have been involved in this issue day and night until now
> 
> would like to confirm the solution actually works before attempting to explain. let's wait for the 12.03 firmware release

Has this been uploaded to the network yet? My six hotspots are still effectively dead since beginning November...

**Comment by Pappa-Bear** [comment]
> > > @amirhaleem
> > > Thank you for your support and cooperation
> > > If possible, tell us and our friends the reason for this problem
> > > We have been involved in this issue day and night until now
> > 
> > 
> > would like to confirm the solution actually works before attempting to explain. let's wait for the 12.03 firmware release
> 
> Has this been uploaded to the network yet? My six hotspots are still effectively dead since beginning November...

I think it safe to assume an announcement would be made on Discord server as this is likely to be a firmware release which are ordinarily communicated there. No announcement as yet, so...keep watching

**Comment by gusosborne** [comment]
> @amirhaleem
> 
> My hotspot stopped witnessing with the last 2021.11.30.1 update. Following the blockchain with no problem. I changed its public IP but still no witnessing. I then changed ISP entirely and the hotspot started witnessing again.
> 
> I've also been doing some investigation. I did a network capture of my hotspot while it was in the situation where it wasn't witnessing anything and the hotspots around were beaconing. I then analyzed the hotspots that beaconed around me in that timeframe and got the IP of the corresponding challengers (with the help of heliumstatus.io). After that, I started searching my network capture for outgoing communication from my hotspot to those challengers. What I found was that my hotspot was reporting witnessing the beacons to the correct challengers (you can even see in the packets the lora datarate of the signal).
> 
> So, my hotspot was indeed receiving the lora beacons and reporting them to the corresponding challengers successfully, but in the eyes of the blockchain my hotspot was never a witness to those beacons. (The beacons have less than 18 witnesses, so there was space for my hotspot to be selected as a witness)
> 
> This makes it seem that is not a peerbook problem since the hotspot knew to which IP to connect to report the witnessing.
> 
> Hotspot is "Cold Sable Snake"
> 
> EDIT: Seems there's already an issue for this, but was closed: #1238

Please open a new issue for this, as long as you can post the relevant network .pcap files to show exactly what is happening (beacons issued, sent,  witnessed, then lost / rejected before they hit the blockchain). This may be the answer..

**Comment by yogeshnichal** [comment]
> I have 7 miners they still earn only 0.03-0.05 HNT per day since last 10 days. They were working fine before, It's outdoor setup, Public/static IP 2 on fiber & 5 on 4G LTE. I am trying to set up an IoT network for my small town so I have all my miners setup close to each other. Please please help ! 😞 https://explorer.helium.com/accounts/13wvymwxsxw6nDbRa5uE5wm76cyDgM1KNKtJVmnXbzd1tmRbQuA

**Comment by bkauii** [comment]
My hotspot will not send or receive beacons. It is in optimal location, I tried changing antenna and cord but did not help. I am using a syncrobit

**Comment by amirhaleem** [comment]
we just announced the 12.06 release which we hope will help: https://engineering.helium.com/2021/12/06/blockchain-release-dns-and-seednode-fixes.html

reminder that it will only be fully effective when most or all of the network has updated, not just your own miners

**Comment by ElYoM** [comment]
@amirhaleem Thanks for the work. Hoping indeed that it solves our problem. We will be patient for a few more days (for some, we are not at this point anymore). ;)

**Comment by Chris-S44** [comment]
> we just announced the 12.06 release which we hope will help: https://engineering.helium.com/2021/12/06/blockchain-release-dns-and-seednode-fixes.html
> 
> reminder that it will only be fully effective when most or all of the network has updated, not just your own miners

Thanks @amirhaleem all my dead sensecaps finally got a witness. Even though sensecap has not pushed the fw to us yet the challenger was a RAK and I believe they get the fw first direct from Helium. Thanks again.

**Comment by cany25** [comment]
My Bobcat has been resurrected. Sent 1 beacon and witnessed 30 times in 24 hours, and its getting better. Thank you!
![grafik](https://user-images.githubusercontent.com/87498131/145021448-ef17abe0-41e9-4eac-bc65-57fe0be3c2d4.png)

**Comment by bgdn021** [comment]
My pisces still dead. Only the error log has changed to this:
2021-12-07 12:22:26.936 [error] <0.6536.0>@libp2p_stream_relay:handle_server_data:193 fail to pass request {libp2p_relay_bridge_cr_pb,"/p2p/112YtvBtaccNRFEhn7ywj4cbKvZa7N7koJYFAfsdYniyjnryxQ8G","/ip4/88.217.86.87/tcp/44158"} Server not found
2021-12-07 12:06:59.324 [error] <0.5803.0>@libp2p_stream_relay:handle_server_data:193 fail to pass request {libp2p_relay_bridge_cr_pb,"/p2p/11Uhns2gE6fUm6H3zdsK3jbdJ9uU155hpY2pHg6cuhkyFYkfo2o","/ip4/103.97.32.53/tcp/44158"} Server not found
2021-12-07 11:56:05.955 [error] <0.5245.0>@libp2p_stream_relay:handle_server_data:193 fail to pass request {libp2p_relay_bridge_cr_pb,"/p2p/112YtvBtaccNRFEhn7ywj4cbKvZa7N7koJYFAfsdYniyjnryxQ8G","/ip4/50.108.245.77/tcp/44158"} Server not found
2021-12-07 11:29:43.690 [error] <0.3797.0>@libp2p_stream_relay:handle_server_data:193 fail to pass request {libp2p_relay_bridge_cr_pb,"/p2p/111MJpAvoeUukVG6P6pZYhTnKeA2UKmVAj8HCcCXTsLHxkfQ2Kf","/ip4/82.79.102.155/tcp/44158"} Server not found
2021-12-07 11:29:35.590 [error] <0.3769.0>@libp2p_stream_relay:handle_server_data:193 fail to pass request {libp2p_relay_bridge_cr_pb,"/p2p/112YtvBtaccNRFEhn7ywj4cbKvZa7N7koJYFAfsdYniyjnryxQ8G","/ip4/24.9.138.240/tcp/44158"} Server not found
2021-12-07 11:10:16.068 [error] <0.2866.0>@libp2p_stream_relay:handle_server_data:193 fail to pass request {libp2p_relay_bridge_cr_pb,"/p2p/111MJpAvoeUukVG6P6pZYhTnKeA2UKmVAj8HCcCXTsLHxkfQ2Kf","/ip4/38.15.94.241/tcp/44158"} Server not found
2021-12-07 11:05:06.320 [error] <0.2576.0>@libp2p_stream_relay:handle_server_data:193 fail to pass request {libp2p_relay_bridge_cr_pb,"/p2p/112YtvBtaccNRFEhn7ywj4cbKvZa7N7koJYFAfsdYniyjnryxQ8G","/ip4/84.64.231.113/tcp/44158"} Server not found

**Comment by taoteh1221** [comment]
> My Bobcat has been resurrected. Sent 1 beacon and witnessed 30 times in 24 hours, and its getting better. Thank you! ![grafik](https://user-images.githubusercontent.com/87498131/145021448-ef17abe0-41e9-4eac-bc65-57fe0be3c2d4.png)

Yes, I think they fixed the network. Can confirm the 12.06 firmware has definitely got me more witnesses then I've ever had before. Thank you Helium team! 👍

**Comment by mathoso** [comment]
no, this is not fixed network yet, 1 witnessed beacon on 3 bobcats today, in 14 hours

![image](https://user-images.githubusercontent.com/72282420/145032301-ec9a35b0-b62d-4df8-ae09-d61eae6b1930.png)
![image](https://user-images.githubusercontent.com/72282420/145032368-4de3bc63-7e30-44ba-bbbb-f9fd63383d56.png)
![image](https://user-images.githubusercontent.com/72282420/145032247-946173b5-5a02-4759-ab57-6771820c24ad.png)

**Comment by Pappa-Bear** [comment]
I suggest giving it a few days to allow things to settle down and then make a judgement call on whether the issue is resolved or not. Activity fluctuates and it's worth trying to look at results over a period of time (like 4 or 5 days minimum), rather than watching it by the hour.

**Comment by Pappa-Bear** [comment]
> I suggest giving it a few days to allow things to settle down and then make a judgement call on whether the issue is resolved or not. Activity fluctuates and it's worth trying to look at results over a period of time (like 4 or 5 days minimum), rather than watching it by the hour.

But I will say I'm quietly confident that things have improved based on my 'control' hotspot that I left on LTE even though it was only challenging every 8-10 hours and doing 1 witness per day for the last 3 or 4 weeks - this spot did it's first beacon 5 hours ago right after the FW update and just sent out another beacon with 18 witnesses and has witnessed a few as well in the 5 hours...so looking positive. However, a few other of my hotspots on LTE have done nothing...but will wait and see over the next 4-5 days before celebrating or swearing.

**Comment by amirhaleem** [comment]
> no, this is not fixed network yet, 1 witnessed beacon on 3 bobcats today, in 14 hours

again as I mentioned above, the entire network has to update in order for it to really be effective, not just your own miners

**Comment by ykuntsevych** [comment]
@amirhaleem 

OK, so basically all these errors will disappear once most hotspots are updated?  In your opinion how long this may take? 

That's my miner: Faint Denim Parrot
I have few guys in my cell getting $15-$20/day and I am not sure they will ever update. Maybe they have never updated their miners before and will never do so.  Looking at these logs below - do you think the issue is with the network? I am not relayed, LAN, Miner Version: miner-arm64_2021.12.06.0_GA



`2021-12-07 22:26:11.035 [error] <0.29403.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 22:25:55.122 [error] <0.29402.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 22:23:43.134 [error] <0.29278.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 22:21:12.932 [error] <0.29193.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 22:20:32.520 [error] <0.29158.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 22:19:02.870 [error] <0.29111.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 22:14:07.744 [error] <0.28961.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 22:09:42.524 [error] <0.28810.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 22:05:43.283 [error] <0.28662.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 21:45:26.352 [error] <0.27922.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 21:33:12.700 [error] <0.27444.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 21:26:55.918 [error] <0.27187.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 21:20:31.076 [error] <0.26918.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 21:16:48.308 [error] <0.26769.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 21:14:06.056 [error] <0.26698.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 21:11:40.664 [error] <0.26525.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 20:50:42.338 [error] <0.1634.0>@miner_poc_statem:handle_targeting:450 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU targeting/challenging failed 3 times back to requesting
2021-12-07 20:50:42.338 [error] <0.1634.0>@miner_poc_statem:handle_challenging:565 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): retries_exceeded
2021-12-07 20:50:32.337 [error] <0.1634.0>@miner_poc_statem:send_onion:1003 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): [{"/ip4/86.245.201.8/tcp/44158",timeout}]
2021-12-07 20:50:17.291 [error] <0.1634.0>@miner_poc_statem:send_onion:1003 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): [{"/ip4/86.245.201.8/tcp/44158",timeout}]
2021-12-07 20:50:02.235 [error] <0.1634.0>@miner_poc_statem:send_onion:1003 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): [{"/ip4/86.245.201.8/tcp/44158",timeout}]
2021-12-07 20:49:56.929 [error] <0.1634.0>@miner_poc_statem:handle_challenging:565 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): retries_exceeded
2021-12-07 20:49:46.928 [error] <0.1634.0>@miner_poc_statem:send_onion:1003 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): [{"/ip4/86.245.201.8/tcp/44158",timeout}]
2021-12-07 20:49:31.819 [error] <0.1634.0>@miner_poc_statem:send_onion:1003 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): [{"/ip4/86.245.201.8/tcp/44158",timeout}]
2021-12-07 20:49:16.727 [error] <0.1634.0>@miner_poc_statem:send_onion:1003 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): [{"/ip4/86.245.201.8/tcp/44158",timeout}]
2021-12-07 20:49:11.477 [error] <0.1634.0>@miner_poc_statem:handle_challenging:565 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): retries_exceeded
2021-12-07 20:49:01.477 [error] <0.1634.0>@miner_poc_statem:send_onion:1003 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): [{"/ip4/86.245.201.8/tcp/44158",timeout}]
2021-12-07 20:48:46.428 [error] <0.1634.0>@miner_poc_statem:send_onion:1003 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): [{"/ip4/86.245.201.8/tcp/44158",timeout}]
2021-12-07 20:48:31.383 [error] <0.1634.0>@miner_poc_statem:send_onion:1003 poc_id=8qcIrCn-KyqSRa2HxANTFS5UKQdFzRGMS3krHvTcVVU failed to dial 1st hotspot ("/p2p/11u8v6Z6KY58XpUDLcuEAY1viRsMc99uiZMWLazvsF1ZADLSW22"): [{"/ip4/86.245.201.8/tcp/44158",timeout}]
2021-12-07 20:42:11.964 [error] <0.25518.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/1136U5GVZd5cSrWfjYbY5JsuUd2i7JfWNdRwvWtf4j5gpxreaCL", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:42:11.963 [error] <0.25514.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/112NhC3ohnghz1nvs8ABLtCdvSgFhF9ZarR64af2wN4CXyYxxGQf", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:42:11.943 [error] <0.25517.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/112rWtqMLotbReMd1LawAerEpSGbs8au7XjipzicnbJzQPfVofBc", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:42:11.942 [error] <0.25512.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/112rmTjX7dY3jB7xtgJ9L6cR7kiBE5X5iSQeyDRwNJZLwmPB1RDX", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:42:11.935 [error] <0.25515.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/1125mcpF4C1ctktvaWWC8mKcGoJYNVd73dyZGCuvEKo7nsWFiKy2", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:41:22.792 [error] <0.25380.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/11XH4CApbGr9NYDfUEPeZN4D4WBJbnzH8ufxnX1kPH37gHmLBcG", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:41:22.788 [error] <0.25377.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/11Fqxc5KCc4WMr9V6AxwGs81m1rVL8ewQkayFX5TrJaCeejmMmV", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:41:22.734 [error] <0.25374.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/112rWtqMLotbReMd1LawAerEpSGbs8au7XjipzicnbJzQPfVofBc", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:41:00.711 [error] <0.25340.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/1125mcpF4C1ctktvaWWC8mKcGoJYNVd73dyZGCuvEKo7nsWFiKy2", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:41:00.709 [error] <0.25344.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/112rWtqMLotbReMd1LawAerEpSGbs8au7XjipzicnbJzQPfVofBc", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:41:00.709 [error] <0.25342.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/14JcxrsQrYGiHKuKAZpvNNji7rBsWsK7Gg2pBwXY46bZNLfX5sU", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:41:00.707 [error] <0.25347.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/112AKmh2YY3Mb1jgoUW8e1zE8pxQDyKUgpmwUkzN7PWx1mSzMGjy", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:41:00.635 [error] <0.25345.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/14qdeawtJrT4UZFhXtiWfH7XdN8AqWEcmJwKwQxBys98ufSAMVr", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:41:00.630 [error] <0.25341.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/14jUgjUuy8rCr6MmfnvzTtXBwzjbYJzbwHtLVaqU8qMAyZGnRCw", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:41:00.629 [error] <0.25346.0>@blockchain_txn_dialer:dial_:142 libp2p_framed_stream dial failed. Reason: not_found, To: "/p2p/11ugSqokseCLarVJxZTsc8GsyviDQymL6WHLLXaMQAAK9ZJHmvt", TxnHash: <<203,216,115,38,91,203,35,0,152,173,163,130,250,192,251,151,132,94,199,59,204,229,165,43,176,97,97,157,139,139,208,138>>
2021-12-07 20:25:27.261 [error] <0.24490.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 20:05:42.616 [error] <0.23731.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 20:03:22.543 [error] <0.23692.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
2021-12-07 20:01:19.172 [error] <0.23559.0>@miner_onion_server:send_witness:207 failed to send witness, max retry
                                           1,1},... error: {invalid,validation_failed}
                                             101,82,73,205,5,49>>,
                                             155,143,238,145,87,216,109,200,
                                             113,53,30,110,174,182,110,174,86,
                                           <<0,196,146,234,51,231,71,69,62,139,
                                          {blockchain_state_channel_summary_v1_pb,
                                           1,2},
                                             69,25,78,175,33,226>>,
                                             136,38,248,58,241,54,204,158,96,
                                             248,75,71,178,195,245,98,113,201,
                                           <<0,212,42,95,140,127,234,174,123,
                                          {blockchain_state_channel_summary_v1_pb,
                                           1,2},
                                             138,154,100,166,169,69>>,
                                             245,213,182,162,154,168,19,29,138,
                                             209,216,15,242,71,99,227,89,250,
                                           <<0,151,246,82,210,196,179,86,17,
                                         [{blockchain_state_channel_summary_v1_pb,
                                         400000,5,
                                           235,186>>,
                                           25,102,104,1,164,251,136,113,9,43,
                                           65,166,42,134,151,108,47,245,207,19,
                                         <<0,76,116,28,92,113,78,76,123,20,163,
                                           173,8,111>>,
                                           96,110,20,242,102,167,55,158,181,
                                           24,93,24,138,71,202,42,43,12,118,87,
                                         <<37,142,178,238,215,102,222,150,162,
2021-12-07 19:59:05.910 [error] <0.23726.0>@blockchain_worker:send_txn:1184 failed to submit txn: type=state_channel_close, state_channel={blockchain_state_channel_v1_pb,
                                           1... error: {invalid,validation_failed}
                                             240,145,189,238,11>>,
                                             134,162,175,189,246,96,191,12,93,
                                             168,63,128,83,235,190,96,19,0,17,
                                           <<0,43,232,49,177,42,116,237,121,
                                          {blockchain_state_channel_summary_v1_pb,
                                           4,8},
                                             12,197,254,31,231>>,
                                             52,185,97,213,254,53,5,70,233,157,
                                             98,211,92,8,249,251,161,149,162,
                                           <<0,180,209,226,106,246,37,213,210,
                                          {blockchain_state_channel_summary_v1_pb,
                                           1,2},
                                             100,81,196,190,30>>,
                                             47,66,152,42,162,102,241,92,41,
                                             202,231,27,46,232,177,37,221,143,
                                           <<0,45,199,44,76,30,167,217,244,212,
                                         [{blockchain_state_channel_summary_v1_pb,
                                         400000,37267,
                                           193,237,106>>,
                                           220,24,59,236,149,26,141,119,81,208,
                                           24,106,74,213,136,24,242,41,172,56,
                                         <<0,122,218,88,133,243,228,11,191,188,
                                           103,188,134>>,`

**Comment by bkauii** [comment]
I have 2 that have no issued or witnessed challenges yet

https://explorer.helium.com/hotspots/112MAoribtafFw3Z66Zv82wuajJTxQVjoeM7v9PRfTorsAepxN6c

https://explorer.helium.com/hotspots/112qPFRwNUEj86jhqLhaPCRTKNEZwsbr5ZUyLkRN5PKe49dyPnRt/activity

**Comment by wetsqueegee** [comment]
not sure if this helps or not but my hotspot https://explorer.helium.com/hotspots/11EDzZijZwpJ9ArrvgLUnv6rATAnJ81VJx93WCYEiMgpREkob13, is now no longer seeing my mapper. it's only connects to surrounding hotspots

**Comment by Pappa-Bear** [comment]
> > I suggest giving it a few days to allow things to settle down and then make a judgement call on whether the issue is resolved or not. Activity fluctuates and it's worth trying to look at results over a period of time (like 4 or 5 days minimum), rather than watching it by the hour.
> 
> But I will say I'm quietly confident that things have improved based on my 'control' hotspot that I left on LTE even though it was only challenging every 8-10 hours and doing 1 witness per day for the last 3 or 4 weeks - this spot did it's first beacon 5 hours ago right after the FW update and just sent out another beacon with 18 witnesses and has witnessed a few as well in the 5 hours...so looking positive. However, a few other of my hotspots on LTE have done nothing...but will wait and see over the next 4-5 days before celebrating or swearing.

![image](https://user-images.githubusercontent.com/95157626/145157864-1ad2a7f9-4c23-49c4-a0ba-b472aa2973f7.png)
The affect of the FW update - no changes in hardware or anything else...just the update the other morning.

**Comment by ebestek** [comment]
![Screenshot_20211208-183140_Chrome](https://user-images.githubusercontent.com/95607188/145236425-4b45643a-8beb-469f-9c85-55076bb18054.jpg)
![Screenshot_20211208-183200_Chrome](https://user-images.githubusercontent.com/95607188/145236438-db0a04b0-6b0b-42bf-8211-03f97cefeb41.jpg)

Still there is no changes, no sending beacon and no increment witness beacon

**Comment by biohazd** [comment]
@amirhaleem @Pappa-Bear 
From your side are you seeing things going well?

after my brief spike in traffic yesterday, it’s pretty much flatlined again.

My guess is as more people updated and starting working again the system couldn’t cope.

**Comment by JeroenIoT** [comment]
**flat and dead""** // 2x RAKv2 miners // one below started around 11th of Nov (syncing state now but that also happened last month)

https://explorer.helium.com/hotspots/112QqrnAVCxJf99YyYTicrGQ56N42fGq3z4f14jE4hBR46wy4Hyu

I can only wait ......

**Comment by ebestek** [comment]
> ![Screenshot_20211208-183140_Chrome](https://user-images.githubusercontent.com/95607188/145236425-4b45643a-8beb-469f-9c85-55076bb18054.jpg)
> ![Screenshot_20211208-183200_Chrome](https://user-images.githubusercontent.com/95607188/145236438-db0a04b0-6b0b-42bf-8211-03f97cefeb41.jpg)
> 
> Still there is no changes, no sending beacon and no increment witness beacon
> 

Now it sent first send beacon after 32days, thanks a lot😀

**Comment by gusosborne** [comment]
My MNTD v1.5 seems to be springing back to life over the past 48 hours- but my RAK (1/4 mile away, never had a problem) has also picked way up today, so this may be coincidental or related to my area - or just luck.

**Comment by bkauii** [comment]
Update: Creamy Dijon Seahorse has begun producing but Wobbly Sangria Jellyfish still has not

> I have 2 that have no issued or witnessed challenges yet
> 
> https://explorer.helium.com/hotspots/112MAoribtafFw3Z66Zv82wuajJTxQVjoeM7v9PRfTorsAepxN6c
> 
> https://explorer.helium.com/hotspots/112qPFRwNUEj86jhqLhaPCRTKNEZwsbr5ZUyLkRN5PKe49dyPnRt/activity [ ![Screenshot_20211208-105824_Brave](https://user-images.githubusercontent.com/89312660/145240701-c82eed0c-878a-45f6-98c7-1c51ad4b0682.jpg) ![Screenshot_20211208-105811_Brave](https://user-images.githubusercontent.com/89312660/145240735-e331bb80-2032-4839-b1f1-b5c288d95623.jpg) ](url)

**Comment by jerome-botreau** [comment]
Since 2021.12.03 update I witness again, but I don't send beacon

**Comment by Vel74** [comment]
Sparkly Cobalt Newt....was flatlined for weeks, the two days of movement, now zero

**Comment by Jamovich** [comment]
Whatever has been done recently seems to have resolved the problem for my hotspots. Thanks helium team

**Comment by leyuansugar** [comment]
https://etl.dewi.org/question/1036-poc-over-time-hotspots-challenging-not-beaconing-daily?Days=5
This is a statistical chart about the issue, thanks to molano in discord.

**Comment by Mikael1993** [comment]
@amirhaleem 
It was good for about 1 to 2 days and again zero

**Comment by jnspsn** [comment]
Yeah mine where working for 24 hours and now they are back to zero.
https://explorer.helium.com/hotspots/112pEwmpuJrn7trHf1xvzz6j3nSKEhwNjqNaL7XwhP7V138PdFA1/activity

**Comment by amirhaleem** [comment]
we think we've found the caused and fixed it with the 12.09 release. even though it affected primarily relayed hotspots, it could cause non-relayed hotspots to have minimal activity:

https://engineering.helium.com/2021/12/09/blockchain-release-libp2p-fix.html

**Comment by bkauii** [comment]
Update: Creamy Dijon Seahorse is consistently producing.
Wobbly Sangria Jellyfish has now witnessed once but has not sent a beacon or witnessed again.


> Update: Creamy Dijon Seahorse has begun producing but Wobbly Sangria Jellyfish still has not
> 
> > I have 2 that have no issued or witnessed challenges yet
> > https://explorer.helium.com/hotspots/112MAoribtafFw3Z66Zv82wuajJTxQVjoeM7v9PRfTorsAepxN6c
> > https://explorer.helium.com/hotspots/112qPFRwNUEj86jhqLhaPCRTKNEZwsbr5ZUyLkRN5PKe49dyPnRt/activity [ ![Screenshot_20211208-105824_Brave](https://user-images.githubusercontent.com/89312660/145240701-c82eed0c-878a-45f6-98c7-1c51ad4b0682.jpg) ![Screenshot_20211208-105811_Brave](https://user-images.githubusercontent.com/89312660/145240735-e331bb80-2032-4839-b1f1-b5c288d95623.jpg) ](url)

**Comment by jnspsn** [comment]
Well, I am certain it didnt help my mines. One that never had a problem went offline
https://explorer.helium.com/hotspots/11UnxfmyiLPZnSF7YqHCnmtkiS94xse2zU6vaBoeboiYdHYuTRS

**Comment by jakub2907** [comment]
Still no change on three miners that I have provided detailed information about earlier. Sporadic witnessing but no beacons sent. The other 8 in my town are working fine.
It's been almost a month and a half now. This is really not looking great guys:( 

https://explorer.helium.com/hotspots/112uukw5t6T1KMUZuxENZdbWrz68UhE6AVafJci7Pcs8TXFXd4bv
https://explorer.helium.com/hotspots/112rLJFZsUjw1sMd29dZUfZuY8jkiCAqeyEHLn4YZ1r9TNPx9qDc
https://explorer.helium.com/hotspots/11wmQytt96ufuYhxboq6tW7tVZ6AqRduuwpYoszLS7sdJT4CWnL

**Comment by mathoso** [comment]
I hope, this is new beginning

![image](https://user-images.githubusercontent.com/72282420/145568039-4947ec87-7d89-432d-9f8f-37c6eeb8ebcd.png)

**Comment by ElYoM** [comment]
Hello,
Thank you for the first fixes deployed which seem to have solved the problem for many of us. However, there are still hotspots that have not yet resumed normal activity. Example with this new hotspot in my city and for which I managed to contact its owner.

Low Tiger Oyster https://explorer.helium.com/hotspots/11YdsNeDpPD4a2tffM3oU6RGbfofH13xP4ZAUwXMstjXtPLCLvN

This hotspot was installed two weeks ago, is perfectly configured (not relayed), is up to date (firmware 2021.12.09.0) and is on a 1Gbps fiber optic connection with the same ISP as my 3 hotspots which have resumed activity. And it has not emitted any beacon since its installation.

I hope that this report can help you to diagnose this problem which persists and thus help other people who would be in the same case.

Thank you for your help.

Edit: another new hotspot in my city also seems to be affected by the 0 beacon problem but I see conflicting information between the Helium explorer and HeliumStatus.io --> Modern Brunette Scorpion https://explorer.helium.com/hotspots/11ofbjWFPXwpvxBUur2uDgv6K1FWvfpBZBvvbi6o8JgK2afVgxp

**Comment by billgeoz** [comment]
So, to my understanding I see 3 kinds of issues here.

1) No beacons transmitted by the hotspot, at all.

2) Beacons are being transmitted by the hotspot, but are not being witnessed.

3) Beacons transmitted and witnessed, but no beacons are received (witnessed) by the hotspot.

Personally I face issue no.3

**Comment by Chris-S44** [comment]
2021. 12.06 was a bit better.
2021.12.09 has made a big difference
All my hotspots working again. Even the one on lte.
Thank you @amirhaleem and team

**Comment by bgdn021** [comment]
> So, to my understanding I see 3 kinds of issues here.
> 
> 1. No beacons transmitted by the hotspot, at all.
> 2. Beacons are being transmitted by the hotspot, but are not being witnessed.
> 3. Beacons transmitted and witnessed, but no beacons are received (witnessed) by the hotspot.
> 
> Personally I face issue no.3

Issue no. 3

**Comment by billgeoz** [comment]
> 

Let's make a list here...
I'll be helpful

**Comment by amirhaleem** [comment]
> So, to my understanding I see 3 kinds of issues here.
> 
> 1. No beacons transmitted by the hotspot, at all.
> 2. Beacons are being transmitted by the hotspot, but are not being witnessed.
> 3. Beacons transmitted and witnessed, but no beacons are received (witnessed) by the hotspot.
> 
> Personally I face issue no.3

#1 is nearly always a local networking issue, such as public IP changing, port forwarding problem, etc. if no one can reach you on the network, then you never end up beaconing

the other two are more difficult to diagnose as there are potential RF aspects to them. in any case you'll want to give it all some time to settle down after yesterday's OTA

**Comment by mathoso** [comment]
it is working, somehow, but I still don't understand, there are some activities today so looking forward, but, the worst miner in october is now the best, and the best miner in october (and few months before, the red one) was killed by network all november, and now last days still only 10-20% witnessing of average hotspot in area, with one of the best location for sure

![image](https://user-images.githubusercontent.com/72282420/145625606-3cd40137-5040-48b7-8f3d-af1a1acb5580.png)

**Comment by JeroenIoT** [comment]
Still **flat and dead**

It has been flattening for over a month and still no beacon, no witness, no data, no earning, no nothing.

https://app.heliumstatus.io/hotspots/112QqrnAVCxJf99YyYTicrGQ56N42fGq3z4f14jE4hBR46wy4Hyu
https://explorer.helium.com/hotspots/112QqrnAVCxJf99YyYTicrGQ56N42fGq3z4f14jE4hBR46wy4Hyu

If anyone has an idea pls let me know (I am not in favor of selling the miners that do work today, however it crossed my mind)

**Comment by amirhaleem** [comment]
> Still **flat and dead**
> 
> It has been flattening for over a month and still no beacon, no witness, no data, no earning, no nothing.
> 
> https://app.heliumstatus.io/hotspots/112QqrnAVCxJf99YyYTicrGQ56N42fGq3z4f14jE4hBR46wy4Hyu https://explorer.helium.com/hotspots/112QqrnAVCxJf99YyYTicrGQ56N42fGq3z4f14jE4hBR46wy4Hyu
> 
> If anyone has an idea pls let me know (I am not in favor of selling the other miners that do work today, however it crossed my mind)

I’d try changing the sdcard to start, but it doesn’t seem related to the issues above as it hasn’t performed *any* activity in a long time

**Comment by JeroenIoT** [comment]
> > Still **flat and dead**
> > It has been flattening for over a month and still no beacon, no witness, no data, no earning, no nothing.
> > https://app.heliumstatus.io/hotspots/112QqrnAVCxJf99YyYTicrGQ56N42fGq3z4f14jE4hBR46wy4Hyu https://explorer.helium.com/hotspots/112QqrnAVCxJf99YyYTicrGQ56N42fGq3z4f14jE4hBR46wy4Hyu
> > If anyone has an idea pls let me know (I am not in favor of selling the other miners that do work today, however it crossed my mind)
> 
> I’d try changing the sdcard to start, but it doesn’t seem related to the issues above as it hasn’t performed _any_ activity in a long time

Thanks for the feedback Amir - appreciated!

Has not crossed my mind to change SD card with the latest fw burned (as hotspot state seems ok). Nevertheless I can try as kind of a "last resort" :-). Will report results here when done (probably after the weekend)

**Comment by jakub2907** [comment]
> > So, to my understanding I see 3 kinds of issues here.
> > 
> > 1. No beacons transmitted by the hotspot, at all.
> > 2. Beacons are being transmitted by the hotspot, but are not being witnessed.
> > 3. Beacons transmitted and witnessed, but no beacons are received (witnessed) by the hotspot.
> > 
> > Personally I face issue no.3
> 
> #1 is nearly always a local networking issue, such as public IP changing, port forwarding problem, etc. if no one can reach you on the network, then you never end up beaconing
> 
> the other two are more difficult to diagnose as there are potential RF aspects to them. in any case you'll want to give it all some time to settle down after yesterday's OTA

I am unfortunatelly watting for #1 to be fixed on mine 3 miners. They are not beaconing, although they were doing fine before. I have not changed anything in the setup. They are not relayed, on a public and static IP. They stoped over a month ago and no fixes were able to wake them up so far.

**Comment by Mikael1993** [comment]
@amirhaleem
Only a very small change maybe 1 tenth of the last
And again zero

**Comment by Jamovich** [comment]
2 of my hotspots are still not functional

Dazzling Arctic Jay
Docile Rosewood Caribou

but others have started working

**Comment by Mikael1993** [comment]
I think a school kid is working on this problem
If it is broken, everyone must be broken
If the network is right, everyone should be right
We have become laboratory mice
Whatever the problem is, it will be tested on us first
For 40 days, our income has reached zero
@amirhaleem Are you really yourself or a school kid?

**Comment by jerome-botreau** [comment]
On my side, all is fixed : 

Witnesses are working again since 21.12.06 update
Beacons are working again since 21.12.09 update 

Thanks to helium team !

**Comment by SeroSerhan** [comment]
after patch 2021.12.09.0, no witness and no beacon problems had been fixed for two days. 
But yesterday again I started to see no activity for 12 hours.  I tried couple of things like reseting router, power cycle hotspot etc. I were using static public IP. When I changed it to dynamic, the activities started again in a couple of minutes. Somehow for the specific IPs, the system is starting to ignore them after a while and when you change the IP, it is getting back to normal.

[Real Pistachio Opossum](https://explorer.helium.com/hotspots/112kATHoGFJg2kcB2CbxH16wGPBt2BLRv625CoU2zLtsewNwdP45)

**Comment by Mikael1993** [comment]
@amirhaleem 
Sends beacon well after the update, but 90% of the beacon have zero witness
I hope it will be resolved soon

![image](https://user-images.githubusercontent.com/94840296/145705955-be457049-b678-4a47-a2fe-62d7d61866de.png)

**Comment by Mikael1993** [comment]
@amirhaleem
Sends beacon well after the update, but 90% of the beacon have zero witness
I hope it will be resolved soon

**Comment by softlion** [comment]
2 hotspots affected with this issue:
Bumpy Gingerbread penguin 
Joyous Gingerbread Albatross

**Comment by Mikael1993** [comment]
the problem is that:
If the network is broken or has problems, why do people work as well as before?
Their helium version is the same as ours
Their hotspot version is the same with us
If they have observed everything well, we have observed it and we have a good configuration and there is no problem on our part.
Why they are happy and enjoy and we should be sad that we are a straight line for a month

@amirhaleem Please do not delete this comment and reply

**Comment by Chris-S44** [comment]
> 

Helium collect data of the network as a whole.
For me these updates have really worked and brought my hotspots back to life.
Network looks healthy and you can see that by the lower rewards being paid out.
Helium said that they are increasing their seed nodes. Make sure your hotspots are setup correctly.

**Comment by Mikael1993** [comment]
> 

Are you willing to be in my place?
Extract 0.5 helium per day with 10 hotspots?

**Comment by Mikael1993** [comment]
@Chris-S44 
Are you willing to be in my place? Extract 0.5 helium per day with 10 hotspots?

**Comment by Chris-S44** [comment]
> @Chris-S44 Are you willing to be in my place? Extract 0.5 helium per day with 10 hotspots?

I was. I was getting 0.02 amongst 5 hotspots. It drove me mad for weeks. I tried everything. Different ip addresses, different ISP's even putting them in relay. Eventually I just returned them all to normal. No more relaying and no more rebooting.
I waited for the updates and 2021.12.09 fixed them.
There are still up and down times but much better now. Almost working properly I could say.
No more zero witness beacons as well.

**Comment by Mikael1993** [comment]
> > @Chris-S44 Are you willing to be in my place? Extract 0.5 helium per day with 10 hotspots?
> 
> I was. I was getting 0.02 amongst 5 hotspots. It drove me mad for weeks. I tried everything. Different ip addresses, different ISP's even putting them in relay. Eventually I just returned them all to normal. No more relaying and no more rebooting. I waited for the updates and 2021.12.09 fixed them. There are still up and down times but much better now. Almost working properly I could say. No more zero witness beacons as well.

Why should we be like this but people like us work well

**Comment by mathoso** [comment]
yes, everybody can say, it is fixed, but that fix is not so good, fixed miners are still witnessing under 20% beacons of other miners in area, to day I see 1 witnessed beacon by 2 fixed miners, very disapointing

![image](https://user-images.githubusercontent.com/72282420/145717342-7a2b242e-e583-4b14-9ce4-722fdce0034a.png)

**Comment by Mikael1993** [comment]
I wish we go back to previous versions of firmware 2021.10.27.0
We dont want progress 😞😞😞

**Comment by mathoso** [comment]
another look, this is not good witnessing for me, and these miners have great location and setup in area, both were working very well in september and october

![image](https://user-images.githubusercontent.com/72282420/145717939-6a71e9c1-387b-42a5-8f2f-d4f1e67f7916.png)

**Comment by bkauii** [comment]
Update: Wobbly Sangria Jellyfish has now sent a few beacons and witnessed a few but the intervals of 1 day in between each is still very low. My rewards have gone from .005hnt/day to .05hnt/day but it is still not right. It has a reward scale of 1.00 and is optimally placed with good antenna. 
> Update: Creamy Dijon Seahorse is consistently producing. Wobbly Sangria Jellyfish has now witnessed once but has not sent a beacon or witnessed again.
> 
> > Update: Creamy Dijon Seahorse has begun producing but Wobbly Sangria Jellyfish still has not
> > > I have 2 that have no issued or witnessed challenges yet
> > > https://explorer.helium.com/hotspots/112MAoribtafFw3Z66Zv82wuajJTxQVjoeM7v9PRfTorsAepxN6c
> > > https://explorer.helium.com/hotspots/112qPFRwNUEj86jhqLhaPCRTKNEZwsbr5ZUyLkRN5PKe49dyPnRt/activity [ ![Screenshot_20211208-105824_Brave](https://user-images.githubusercontent.com/89312660/145240701-c82eed0c-878a-45f6-98c7-1c51ad4b0682.jpg) ![Screenshot_20211208-105811_Brave](https://user-images.githubusercontent.com/89312660/145240735-e331bb80-2032-4839-b1f1-b5c288d95623.jpg) ](url)

**Comment by Mikael1993** [comment]
Has 50 witnesses
Witnessed Beacon every 2 minutes and earns hnt
We just look

![image](https://user-images.githubusercontent.com/94840296/145724796-001e1051-1b0c-465f-9838-dbe902c1ad95.png)

https://explorer.helium.com/hotspots/112wCgpp4n9WF6KkGTxiJaa9zNiFbee76f28P5a7DyQFN28QvdJ3/activity

**Comment by mathoso** [comment]
nice, he found some magic

![image](https://user-images.githubusercontent.com/72282420/145725088-201d8b66-d140-49ae-8950-da9f2ea230c4.png)

**Comment by Mikael1993** [comment]
> nice, he found some magic
> 
> ![image](https://user-images.githubusercontent.com/72282420/145725088-201d8b66-d140-49ae-8950-da9f2ea230c4.png)

We do not want magic
It is enough for us to be like before 😞😞😞

**Comment by Carlito751** [comment]
Crazy chartreuse tadpole
Sent beacon and has 165 witness, but don’t witness any beacons or invalid ones for more than 3 weeks

**Comment by ElChelhi92** [comment]
![C79F328B-B6E8-438A-A8BE-ADDC510CD37C](https://user-images.githubusercontent.com/96050569/145788994-f34e1658-4d05-4021-ad46-abcab1fd1819.png)
![8FFA7BEF-E344-4066-8492-AA41BD325BA1](https://user-images.githubusercontent.com/96050569/145788999-a959be1c-112d-4394-82e6-84ddd9d2b4f7.png)


I have this problems to please help me… 0 witness since 4 days

**Comment by softlion** [comment]
> Crazy chartreuse tadpole Sent beacon and has 165 witness, but don’t witness any beacons or invalid ones for more than 3 weeks

Same issue.

**Comment by ElChelhi92** [comment]
Support helium is here ? We have to contact us

**Comment by mathoso** [comment]
2 witnessed beacons, all around can witness 15 times more

![image](https://user-images.githubusercontent.com/72282420/145791954-6417016e-ec79-4a41-8034-9f761f67cc77.png)
![image](https://user-images.githubusercontent.com/72282420/145791912-b19391ff-32a5-43f2-a4e7-447847af5555.png)

**Comment by CallableSwap** [comment]
> 2 witnessed beacons, all around can witness 15 times more
> 
> ![image](https://user-images.githubusercontent.com/72282420/145791954-6417016e-ec79-4a41-8034-9f761f67cc77.png) ![image](https://user-images.githubusercontent.com/72282420/145791912-b19391ff-32a5-43f2-a4e7-447847af5555.png)

Same issue here:
https://explorer.helium.com/hotspots/1124XUwAHFzcfvfMDRAwndNyKZpXYSytifCov1m6bENSJRdxePm6/activity

**Comment by Mikael1993** [comment]
Watering someone who is dead
Does not revive him

**Comment by bgdn021** [comment]
So we are left to ourselves. It is up to us to find an escape from this problem or we just bought some really expensive bricks. 🧱 
The helium team left us. All their resources are directed to light hotspots and more profit.

**Comment by Mikael1993** [comment]
@bgdn021
@amirhaleem 
We must not run away
We need to know why the others are doing well and we are so crazy
I have invited hundreds of people to do this and they have trusted me
For the helium team, only the number of important points matters. They do not care about us and they just pretend.

**Comment by amirhaleem** [comment]
one more release coming today that may help further. please keep the hyperbole and FUD out of this thread or I’ll lock it

**Comment by Mikael1993** [comment]
Thank you

**Comment by Jamovich** [comment]
> one more release coming today that may help further. please keep the hyperbole and FUD out of this thread or I’ll lock it

Hi 

2 of my hotspots have been “syncing” for more than a week.

Docile rosewood caribou (new hotspot installed over a week ago) and Dazzling arctic Jay (last recorded activity was 9 days ago) 

is this also a symptom of the same issue here? If not how to fix it?

thanks

**Comment by jnspsn** [comment]
I have five mines in a small town. Two of them was on lte and was not keeping up with blocks. The latest fix made both of them work perfectly. The strange this is that two of them that never had a problem and is using fibre internet is now only creating challenges.
like this one https://explorer.helium.com/hotspots/115fPQjn8dfrD1PxB343kZbDerSJMAbN7hHbWYJSoWx2yLqmDnJ

**Comment by taoteh1221** [comment]
7 days with zero witnesses. Usually get at least 1 or 2 every few days.

**Comment by jnspsn** [comment]
@amirhaleem It did help me and now all of my mines is up and running. Thank you so much for helping

**Comment by abhay** [comment]
I'm glad to hear that some of the folks on this thread are seeing some improvements with the latest releases. I'm going to close this and create a new one that's specifically: `2021.12.14 reports`. Assuming your manufacturer has upgraded you to this version and you can confirm this and you're still seeing something that's not expected, please repost there.

Trying something new to see if we can coordinate based on release version.
